name: app_user
description: "Lifestyle related diseases"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dio: 5.4.3+1
  easy_localization: ^3.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_gen: ^5.4.0
  flutter_secure_storage: ^9.0.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.0.2
  hive_flutter: ^1.1.0
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  rxdart: ^0.27.7
  talker_bloc_logger: ^4.2.0
  talker_dio_logger: ^4.1.5
  talker_flutter: ^4.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.2
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  pubspec_dependency_sorter: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
  assets:
    outputs:
      class_name: Assets
      package_parameter_enabled: false
    enabled: true
  fonts:
    outputs:
      class_name: AppFonts
    enabled: true
  line_length: 80
flutter:
  uses-material-design: true
